openapi: 3.0.0
info:
  title: Password Reset API
  description: Réinitialisation de mot de passe pour médecins et administrateurs
  version: 1.0.0

paths:
  /v1/auth/password/forgot:
    post:
      tags:
        - Réinitialisation Mot de Passe
      summary: Demander une réinitialisation de mot de passe
      description: |
        Génère un code de réinitialisation envoyé par email ou SMS.
        
        **Utilisateurs autorisés :**
        - ✅ **Médecins validés**
        - ✅ **Administrateurs**
        - ❌ **Patients** (utilisent uniquement l'OTP SMS)
        
        **Méthodes d'envoi :**
        - **Email fourni** → Envoi par email avec template
        - **Téléphone fourni** → Envoi par SMS
        
        **Sécurité :**
        - Code valide **30 minutes**
        - **Anciens codes supprimés** automatiquement
        - **Vérifications** : compte actif, médecin validé

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Adresse email du compte (médecin/admin)
                  example: "dr.fatou.diabate@email.com"
                telephone:
                  type: string
                  pattern: '^[0-9]{8,10}$'
                  description: Numéro de téléphone (8-10 chiffres)
                  example: "0102030405"
              oneOf:
                - required: [email]
                - required: [telephone]
            examples:
              par_email:
                summary: Réinitialisation par email
                value:
                  email: "dr.fatou.diabate@email.com"
              par_telephone:
                summary: Réinitialisation par SMS
                value:
                  telephone: "0102030405"

      responses:
        '200':
          description: Code de réinitialisation envoyé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Code de réinitialisation envoyé"
                  data:
                    type: object
                    properties:
                      method:
                        type: string
                        enum: [EMAIL, SMS]
                        description: Méthode d'envoi utilisée
                        example: "EMAIL"
                      destination:
                        type: string
                        description: Destination d'envoi (email ou téléphone)
                        example: "dr.fatou.diabate@email.com"
                      expiresIn:
                        type: integer
                        description: Durée de validité en minutes
                        example: 30
                      token:
                        type: string
                        description: Token pour le reset (optionnel pour le frontend)
                        example: "abc123def456..."
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-07-24T14:30:22.123Z"

        '400':
          description: Erreur de validation ou utilisateur non autorisé
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    enum: 
                      - USER_NOT_FOUND
                      - WRONG_USER_TYPE
                      - ACCOUNT_INACTIVE
                      - DOCTOR_NOT_VALIDATED
                      - VALIDATION_ERROR
                    example: "USER_NOT_FOUND"
                  message:
                    type: string
                    example: "Aucun compte associé à cette adresse email"
                  data:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "USER_NOT_FOUND"
                      message:
                        type: string
                        example: "Aucun compte associé à cette adresse email"
                  timestamp:
                    type: string
                    format: date-time

        '500':
          description: Erreur serveur lors de l'envoi
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "SEND_FAILED"
                  message:
                    type: string
                    example: "Impossible d'envoyer le code de réinitialisation"

  /v1/auth/password/reset:
    post:
      tags:
        - Réinitialisation Mot de Passe
      summary: Réinitialiser le mot de passe avec token et code
      description: |
        Finalise la réinitialisation du mot de passe avec le token reçu et le code de vérification.
        
        **Processus :**
        1. **Token** reçu par email/SMS lors du `/forgot`
        2. **Code à 6 chiffres** reçu par email/SMS
        3. **Nouveau mot de passe** défini par l'utilisateur
        
        **Sécurité :**
        - Token et code **doivent correspondre**
        - Token valide **30 minutes** maximum
        - **Déconnexion automatique** de toutes les sessions
        - **Ancien mot de passe révoqué**

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - code
                - newPassword
              properties:
                token:
                  type: string
                  minLength: 32
                  description: Token de réinitialisation reçu par email/SMS
                  example: "abc123def456ghi789jkl012mno345pqr678stu901vwx234yz567"
                code:
                  type: string
                  pattern: '^[0-9]{6}$'
                  description: Code de vérification à 6 chiffres
                  example: "123456"
                newPassword:
                  type: string
                  minLength: 8
                  maxLength: 100
                  description: Nouveau mot de passe (min 8 caractères)
                  example: "NouveauMotDePasse123!"
            examples:
              reset_complet:
                summary: Réinitialisation complète
                value:
                  token: "abc123def456ghi789jkl012mno345pqr678stu901vwx234yz567"
                  code: "123456"
                  newPassword: "NouveauMotDePasse123!"

      responses:
        '200':
          description: Mot de passe réinitialisé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Mot de passe réinitialisé avec succès"
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "Votre mot de passe a été modifié. Vous pouvez maintenant vous connecter."
                      redirectToLogin:
                        type: boolean
                        description: Indication pour rediriger vers la connexion
                        example: true
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-07-24T14:30:22.123Z"

        '400':
          description: Token invalide, code incorrect ou erreur de validation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    enum:
                      - INVALID_TOKEN
                      - INVALID_CODE
                      - ACCOUNT_INACTIVE
                      - VALIDATION_ERROR
                    example: "INVALID_CODE"
                  message:
                    type: string
                    example: "Le code de réinitialisation est incorrect"
                  data:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "INVALID_CODE"
                      message:
                        type: string
                        example: "Le code de réinitialisation est incorrect"
                  timestamp:
                    type: string
                    format: date-time

        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "INTERNAL_ERROR"
                  message:
                    type: string
                    example: "Erreur interne du serveur"